---
# vars file for deploy-bulkupload-service

# For script
template_compose_file_name: bulk-upload-service.j2
template_env_file_name: bulk-upload-env.j2
compose_file_name: "{{ service_bulk_upload_service }}.yml"
env_file_name: "{{ service_bulk_upload_service }}.env"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
user_friendly_name: Bulk upload service

# For service
application_port: "{{ service_bulk_upload_port }}"
image_name: "{{ image_bulk_upload_service }}"
tag: "{{ tags_bulk_upload_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_bulk_upload_service }}"
reserved_memory: "{{ service_mem_reserved_bulk_upload_service }}"
limited_memory: "{{ service_mem_limit_bulk_upload_service }}"
health_check_endpoint: http://127.0.0.1:{{ docker_port }}
network_alias_name: "{{ network_alias_bulk_upload_service }}"
docker_service_stack_name: lms
docker_service_name: "{{ service_bulk_upload_service }}"
force_reload: "{{ force_reload_bulk_upload_service }}"
host_mount: "{{ bulk_upload_logs_path }}"
docker_mount: /usr/src/upload/log

# For application
dbs_used: cassandra
sunbird_sso_url: "{{ keycloak_domain }}"
sunbird_sso_realm: "{{ keycloak_sso_realm }}"
sunbird_sso_username: "{{ keycloak_sso_admin_user }}"
sunbird_sso_password: "{{ keycloak_sso_admin_user_password }}"
sunbird_sso_client_id: admin-cli

cassandra_contact_points: "{{ cassandra_host }}:{{ cassandra_port }}"