### Default variable file for lms-service ###

namespace: dev
imagepullsecrets: devregistrysecret
dockerhub: eagle-docker.tarento.com


env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: profanity-filter
image_tag: wn-silver
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 5000
  targetport: 5000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

ui_proxies_bulk_upload: /mydata/bulk_upload


