mysql_host: 
mysql_username: 
mysql_password: 
frac_service_cloud_storage_type: 

learningservice_ip: 
cbp_portal_url: 

ui_proxy_cors_environment: 
##################################

KEYCLOAK_HELPER_SERVICE_CLIENT_ID: 
KEYCLOAK_HELPER_SERVICE_CLIENT_SECRET: 
X_CHANNEL_ID: 

kc_new_user_default_pwd: 
iap_client_secret: 

react_app_api_url: 



#WAT Variables
wat_database: 
wat_ip_address: 
wat_mysql_host: 
wat_mysql_username: 
wat_mysql_password: 

#VEGA Service
vega_api_url:
vega_sandbox_url:
vega_router_url:
vega_compiler_url:
vega_git_access_token:
vega_model_home:
vega_git_branch:
vega_git_username:
vega_git_password:

#UI-STATIC Variables

igot_portal_name: 
igot_portal_env: 

igot_organisation: 
igot_framework: 
igot_channelid: 
igot_azurehost: 
igot_karmayoggiazurebucket: 
igot_azurebucket: 
igot_azureoldhost: 
igot_azureoldbuket: 
karmayogi_portal_url: 
mdo_portal_url: 
spv_portal_url: 
cbp_domain_name: 
igot_karmayoggirules: 
igot_cbprules: 
igot_cbcrules: 
igot_mdorules: 
igot_spvrules: 

###########single-image-backen-URL-conf-for stage##################
react_app_wat_api_url:
react_app_pmdash_api_url:
react_app_vega_api_url:
react_app_vega_sandbox_url:
react_app_vega_router_url:
react_app_vega_compiler_url:
react_app_git_access_token:
################################



react_app_frac_api_url: 
react_app_frac_keycloak_url: 
react_app_frac_proxy_url: 
react_app_frac_socket_url: 
react_app_frac_collab_node_url: 
react_app_frac_user_api_key: 

frac_role_verification: 
frac_notification_url:
frac_auth_api_key: 
ui_proxy_cors_environment: 


#########################sb-cb-ext-variables######
pyeval_server_ip: 
pyeval_server_port: 

iap_server_ip: 
iap_server_port: 
log_access_key: 
#########################################

#######vega-console#######
bot_server_ip: 
bezkoder_app_jwtsecret: 
################
######pm-analytics####

esindexer_secondary_service_host_name: 
esindexer_ternary_host: 
esindexer_secondary_host_port: 
##############################
java_api_base_ip: 
java_api_base_port: 
mysql_wat_be_port: 

neo4j_url: 
kafka_ip: 

##############
send_notification_token: 
frac_url:
cloud_provider: 

react_app_pmdash_prototype_url:  
